### ISSUE TITLE
Link Checker Workflow is failing 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#105]
We have a link checker workflow in the repository (relevant issue #85). However, it is not working as expected ([see logs](https://github.com/json-schema-org/tour/actions/runs/11622263479)) 
We need to fix the workflow

**Comment by heysujal** [comment]
Hi @JeelRajodiya , was this working earlier when you merged it?

After reading the logs, I think the problem here is that you need to make a GitHub(or OAuth app) probably and get access token etc which you have to put in environment variables/secrets of tour repository.

Basically, all the steps to setup a github action.

**Comment by aialok** [comment]
@heysujal @JeelRajodiya Our JSON Schema bot isn’t installed in this repository, which is why it’s failing.

One option is to remove those steps and just use GITHUB_TOKEN, which is a universal token that should work or don’t use any token, though, we might hit GitHub’s rate limits.

@JeelRajodiya Another option is to install the JSON Schema bot in this repository, which should fix this issue.

Thanks

**Comment by JeelRajodiya** [comment]
@heysujal 
> Hi @JeelRajodiya , was this working earlier when you merged it?
No, I don't think so. The logs I have shared are for the first time when the workflow ran.

**Comment by JeelRajodiya** [comment]
> @heysujal @JeelRajodiya Our JSON Schema bot isn’t installed in this repository, which is why it’s failing.
> 
> One option is to remove those steps and just use GITHUB_TOKEN, which is a universal token that should work or don’t use any token, though, we might hit GitHub’s rate limits.
> 
> @JeelRajodiya Another option is to install the JSON Schema bot in this repository, which should fix this issue.
> 
> Thanks

@aialok Thanks for the reply. 

Can you share any docs, using which I can install the bot. I think I don't have the permission to install bots.

**Comment by aialok** [comment]
> > @heysujal @JeelRajodiya Our JSON Schema bot isn’t installed in this repository, which is why it’s failing.
> > One option is to remove those steps and just use GITHUB_TOKEN, which is a universal token that should work or don’t use any token, though, we might hit GitHub’s rate limits.
> > @JeelRajodiya Another option is to install the JSON Schema bot in this repository, which should fix this issue.
> > Thanks
> 
> @aialok Thanks for the reply.
> 
> Can you share any docs, using which I can install the bot. I think I don't have the permission to install bots.

@benjagm has permission to do it.

We transitioned to GitHub app authentication during GSoC. If we simply install the GitHub bot in this repository, everything will work.

By the way, you can also use your PAT for authentication.

**Comment by JeelRajodiya** [comment]
@benjagm Can you please install the JSON-Schema bot in this repo as well?

**Comment by benjagm** [comment]
> @benjagm Can you please install the JSON-Schema bot in this repo as well?

Done. Sorry for the late response.

**Comment by JeelRajodiya** [comment]
Thanks you. The workflow is working as expected 🚀
[Logs](https://github.com/json-schema-org/tour/actions/runs/11622263479)
