### ISSUE TITLE
Use the better-ajv-errors js output format to show the errors right into the editor 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#23]
> I am not sure if this is possible, 

better-ajv-errors has an api which points directly to the error line number ([API link](https://github.com/atlassian/better-ajv-errors?tab=readme-ov-file#format)). We can use the data returned by the api to display errors right into the editor. 

For this to work, we need to find out if the code editor supports showing custom errors

**Comment by JeelRajodiya** [comment]
We can even make use of this - https://github.com/apideck-libraries/better-ajv-errors

**Comment by jdesrosiers** [comment]
`better-ajv-errors` is great (both of them), but it uses the ajv proprietary output format and using ajv for this project isn't a viable option due to bugs, lack of maintenance, and lack of intent to keep up with future spec developments.

Using `better-ajv-errors` will only be possible if you can convert the output of another more reliable implementation into the ajv output format. Then you can pass that to `better-ajv-errors`. I don't think that conversion is possible with `@hyperjump/json-schema`, which is really your only option if you expect this to run in the browser. (I don't remember why I don't think it will work. I remember I tried one time and failed.)

**Comment by JeelRajodiya** [comment]
Thanks @jdesrosiers. currently I am using `@exodus/schemasafe` in the project. 
I am also trying to use `hyperjump/json-schema` for validation. but it is throwing some errors (please view the screenshot below) 

The code for hyperjump validation is available [here](https://github.com/json-schema-org/tour/blob/testcases-migrate/lib/validators.ts#L33). 
I think this error is showing because of the asynchronous nature or I don't know how to use it. Please let me know if you can spot my mistake

![image](https://github.com/json-schema-org/tour/assets/63534268/76c42a72-3e63-4b03-9ccf-9a30f0c9a4ce)

**Comment by JeelRajodiya** [comment]
**Fixed!**. We are now using hyperjump in the project
