### ISSUE TITLE
Implication lesson is missing a test case

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/tour#66]
The following schema passes the Implication lesson, but it has a bug.

```json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "isStudent": {
      "type": "boolean"
    }
  },
  "required": [
    "name"
  ],
  "if": {
    "properties": {
      "isStudent": { "const": true }
    }
  },
  "then": { "required": ["age"] }
}
```

The instance `{ "name": "Jason" }` should be valid according to the prompt, but fails saying that the "age" property is required.

The correct `if` schema should be,

```json
  "if": {
    "properties": {
      "isStudent": { "const": true }
    },
    "required": ["isStudent"]
  },
```

This is a very common error with this kind of constraint and we should be checking for it.

**Comment by michaelmior** [comment]
@jdesrosiers Indeed, I made this error myself when going through the tour and it wasn't until I saw this that I realized my mistake. I think it would also be helpful to include a hint about this or some kind of explanation in the instructions. I think it's somewhat non-obvious and some users might get stuck otherwise.
